# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_AddDeckWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddDeckWidget(object):
    def setupUi(self, AddDeckWidget):
        AddDeckWidget.setObjectName("AddDeckWidget")
        AddDeckWidget.resize(285, 370)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddDeckWidget.sizePolicy().hasHeightForWidth())
        AddDeckWidget.setSizePolicy(sizePolicy)
        AddDeckWidget.setMinimumSize(QtCore.QSize(200, 350))
        AddDeckWidget.setStyleSheet("QWidget#DeckWidget {\n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(AddDeckWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addPushButton = QtWidgets.QPushButton(AddDeckWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addPushButton.sizePolicy().hasHeightForWidth())
        self.addPushButton.setSizePolicy(sizePolicy)
        self.addPushButton.setMinimumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.addPushButton.setFont(font)
        self.addPushButton.setStyleSheet("QPushButton#addPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#addPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#addPushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.addPushButton.setObjectName("addPushButton")
        self.horizontalLayout_2.addWidget(self.addPushButton)

        self.retranslateUi(AddDeckWidget)
        QtCore.QMetaObject.connectSlotsByName(AddDeckWidget)

    def retranslateUi(self, AddDeckWidget):
        _translate = QtCore.QCoreApplication.translate
        AddDeckWidget.setWindowTitle(_translate("AddDeckWidget", "Form"))
        self.addPushButton.setText(_translate("AddDeckWidget", "+"))
import resources.qrc_resources_rc
