# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_CardsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CardsWindow(object):
    def setupUi(self, CardsWindow):
        CardsWindow.setObjectName("CardsWindow")
        CardsWindow.resize(1270, 622)
        self.centralwidget = QtWidgets.QWidget(CardsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.goBackPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.goBackPushButton.setStyleSheet("QPushButton#goBackPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#goBackPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#goBackPushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.goBackPushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/go_back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.goBackPushButton.setIcon(icon)
        self.goBackPushButton.setIconSize(QtCore.QSize(40, 40))
        self.goBackPushButton.setObjectName("goBackPushButton")
        self.horizontalLayout.addWidget(self.goBackPushButton)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("backgroud-color: rgb(210, 210, 210);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1270, 511))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_layout = QtWidgets.QGridLayout()
        self.main_layout.setObjectName("main_layout")
        self.horizontalLayout_2.addLayout(self.main_layout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        CardsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CardsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1270, 26))
        self.menubar.setObjectName("menubar")
        CardsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CardsWindow)
        self.statusbar.setObjectName("statusbar")
        CardsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CardsWindow)
        QtCore.QMetaObject.connectSlotsByName(CardsWindow)

    def retranslateUi(self, CardsWindow):
        _translate = QtCore.QCoreApplication.translate
        CardsWindow.setWindowTitle(_translate("CardsWindow", "MainWindow"))
import resources.qrc_resources_rc
