# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_CardRedactorWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CardRedactorWidget(object):
    def setupUi(self, CardRedactorWidget):
        CardRedactorWidget.setObjectName("CardRedactorWidget")
        CardRedactorWidget.resize(960, 629)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(CardRedactorWidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frontSideEditor = QtWidgets.QTextBrowser(CardRedactorWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.frontSideEditor.setFont(font)
        self.frontSideEditor.setReadOnly(False)
        self.frontSideEditor.setObjectName("frontSideEditor")
        self.verticalLayout_2.addWidget(self.frontSideEditor)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.htmlToFromTextFrontPushButton = QtWidgets.QPushButton(CardRedactorWidget)
        self.htmlToFromTextFrontPushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.htmlToFromTextFrontPushButton.sizePolicy().hasHeightForWidth())
        self.htmlToFromTextFrontPushButton.setSizePolicy(sizePolicy)
        self.htmlToFromTextFrontPushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.htmlToFromTextFrontPushButton.setFont(font)
        self.htmlToFromTextFrontPushButton.setStyleSheet("QPushButton#htmlToFromTextFrontPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#htmlToFromTextFrontPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#htmlToFromTextFrontPushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.htmlToFromTextFrontPushButton.setIconSize(QtCore.QSize(40, 40))
        self.htmlToFromTextFrontPushButton.setObjectName("htmlToFromTextFrontPushButton")
        self.horizontalLayout_3.addWidget(self.htmlToFromTextFrontPushButton)
        self.boldTextFrontPushButton = QtWidgets.QPushButton(CardRedactorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boldTextFrontPushButton.sizePolicy().hasHeightForWidth())
        self.boldTextFrontPushButton.setSizePolicy(sizePolicy)
        self.boldTextFrontPushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.boldTextFrontPushButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.boldTextFrontPushButton.setStyleSheet("QPushButton#boldTextFrontPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#boldTextFrontPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#boldTextFrontPushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.boldTextFrontPushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/bold_text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boldTextFrontPushButton.setIcon(icon)
        self.boldTextFrontPushButton.setIconSize(QtCore.QSize(40, 40))
        self.boldTextFrontPushButton.setObjectName("boldTextFrontPushButton")
        self.horizontalLayout_3.addWidget(self.boldTextFrontPushButton)
        self.italicTextFrontPushButton = QtWidgets.QPushButton(CardRedactorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.italicTextFrontPushButton.sizePolicy().hasHeightForWidth())
        self.italicTextFrontPushButton.setSizePolicy(sizePolicy)
        self.italicTextFrontPushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.italicTextFrontPushButton.setStyleSheet("QPushButton#italicTextFrontPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#italicTextFrontPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#italicTextFrontPushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.italicTextFrontPushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/italic_text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.italicTextFrontPushButton.setIcon(icon1)
        self.italicTextFrontPushButton.setIconSize(QtCore.QSize(40, 40))
        self.italicTextFrontPushButton.setObjectName("italicTextFrontPushButton")
        self.horizontalLayout_3.addWidget(self.italicTextFrontPushButton)
        self.underlinedTextFrontPushButton = QtWidgets.QPushButton(CardRedactorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.underlinedTextFrontPushButton.sizePolicy().hasHeightForWidth())
        self.underlinedTextFrontPushButton.setSizePolicy(sizePolicy)
        self.underlinedTextFrontPushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.underlinedTextFrontPushButton.setStyleSheet("QPushButton#underlinedTextFrontPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#underlinedTextFrontPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#underlinedTextFrontPushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.underlinedTextFrontPushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/underlined_text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.underlinedTextFrontPushButton.setIcon(icon2)
        self.underlinedTextFrontPushButton.setIconSize(QtCore.QSize(40, 40))
        self.underlinedTextFrontPushButton.setObjectName("underlinedTextFrontPushButton")
        self.horizontalLayout_3.addWidget(self.underlinedTextFrontPushButton)
        self.addImageToFrontPushButton = QtWidgets.QPushButton(CardRedactorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addImageToFrontPushButton.sizePolicy().hasHeightForWidth())
        self.addImageToFrontPushButton.setSizePolicy(sizePolicy)
        self.addImageToFrontPushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.addImageToFrontPushButton.setStyleSheet("QPushButton#addImageToFrontPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#addImageToFrontPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#addImageToFrontPushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.addImageToFrontPushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/add_image.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addImageToFrontPushButton.setIcon(icon3)
        self.addImageToFrontPushButton.setIconSize(QtCore.QSize(40, 40))
        self.addImageToFrontPushButton.setObjectName("addImageToFrontPushButton")
        self.horizontalLayout_3.addWidget(self.addImageToFrontPushButton)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.horizontalLayout_3.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(0, 8)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.reverseSideEditor = QtWidgets.QTextBrowser(CardRedactorWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.reverseSideEditor.setFont(font)
        self.reverseSideEditor.setReadOnly(False)
        self.reverseSideEditor.setObjectName("reverseSideEditor")
        self.verticalLayout_3.addWidget(self.reverseSideEditor)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.htmlToFromTextReversePushButton = QtWidgets.QPushButton(CardRedactorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.htmlToFromTextReversePushButton.sizePolicy().hasHeightForWidth())
        self.htmlToFromTextReversePushButton.setSizePolicy(sizePolicy)
        self.htmlToFromTextReversePushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.htmlToFromTextReversePushButton.setFont(font)
        self.htmlToFromTextReversePushButton.setStyleSheet("QPushButton#htmlToFromTextReversePushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#htmlToFromTextReversePushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#htmlToFromTextReversePushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.htmlToFromTextReversePushButton.setIconSize(QtCore.QSize(40, 40))
        self.htmlToFromTextReversePushButton.setObjectName("htmlToFromTextReversePushButton")
        self.horizontalLayout_4.addWidget(self.htmlToFromTextReversePushButton)
        self.boldTextReversePushButton = QtWidgets.QPushButton(CardRedactorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boldTextReversePushButton.sizePolicy().hasHeightForWidth())
        self.boldTextReversePushButton.setSizePolicy(sizePolicy)
        self.boldTextReversePushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.boldTextReversePushButton.setStyleSheet("QPushButton#boldTextReversePushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#boldTextReversePushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#boldTextReversePushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.boldTextReversePushButton.setText("")
        self.boldTextReversePushButton.setIcon(icon)
        self.boldTextReversePushButton.setIconSize(QtCore.QSize(40, 40))
        self.boldTextReversePushButton.setObjectName("boldTextReversePushButton")
        self.horizontalLayout_4.addWidget(self.boldTextReversePushButton)
        self.italicTextReversePushButton = QtWidgets.QPushButton(CardRedactorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.italicTextReversePushButton.sizePolicy().hasHeightForWidth())
        self.italicTextReversePushButton.setSizePolicy(sizePolicy)
        self.italicTextReversePushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.italicTextReversePushButton.setStyleSheet("QPushButton#italicTextReversePushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#italicTextReversePushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#italicTextReversePushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.italicTextReversePushButton.setText("")
        self.italicTextReversePushButton.setIcon(icon1)
        self.italicTextReversePushButton.setIconSize(QtCore.QSize(40, 40))
        self.italicTextReversePushButton.setObjectName("italicTextReversePushButton")
        self.horizontalLayout_4.addWidget(self.italicTextReversePushButton)
        self.underlinedTextReversePushButton = QtWidgets.QPushButton(CardRedactorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.underlinedTextReversePushButton.sizePolicy().hasHeightForWidth())
        self.underlinedTextReversePushButton.setSizePolicy(sizePolicy)
        self.underlinedTextReversePushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.underlinedTextReversePushButton.setStyleSheet("QPushButton#underlinedTextReversePushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#underlinedTextReversePushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#underlinedTextReversePushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.underlinedTextReversePushButton.setText("")
        self.underlinedTextReversePushButton.setIcon(icon2)
        self.underlinedTextReversePushButton.setIconSize(QtCore.QSize(40, 40))
        self.underlinedTextReversePushButton.setObjectName("underlinedTextReversePushButton")
        self.horizontalLayout_4.addWidget(self.underlinedTextReversePushButton)
        self.addImageToReversePushButton = QtWidgets.QPushButton(CardRedactorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addImageToReversePushButton.sizePolicy().hasHeightForWidth())
        self.addImageToReversePushButton.setSizePolicy(sizePolicy)
        self.addImageToReversePushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.addImageToReversePushButton.setStyleSheet("QPushButton#addImageToReversePushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#addImageToReversePushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#addImageToReversePushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.addImageToReversePushButton.setText("")
        self.addImageToReversePushButton.setIcon(icon3)
        self.addImageToReversePushButton.setIconSize(QtCore.QSize(40, 40))
        self.addImageToReversePushButton.setObjectName("addImageToReversePushButton")
        self.horizontalLayout_4.addWidget(self.addImageToReversePushButton)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 1)
        self.horizontalLayout_4.setStretch(4, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.setStretch(0, 8)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(100, -1, 100, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.savePushButton = QtWidgets.QPushButton(CardRedactorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savePushButton.sizePolicy().hasHeightForWidth())
        self.savePushButton.setSizePolicy(sizePolicy)
        self.savePushButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.savePushButton.setFont(font)
        self.savePushButton.setStyleSheet("QPushButton#savePushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#savePushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#savePushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.savePushButton.setObjectName("savePushButton")
        self.horizontalLayout_2.addWidget(self.savePushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 9)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout)

        self.retranslateUi(CardRedactorWidget)
        QtCore.QMetaObject.connectSlotsByName(CardRedactorWidget)

    def retranslateUi(self, CardRedactorWidget):
        _translate = QtCore.QCoreApplication.translate
        CardRedactorWidget.setWindowTitle(_translate("CardRedactorWidget", "Редактирование карты"))
        self.frontSideEditor.setHtml(_translate("CardRedactorWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.frontSideEditor.setPlaceholderText(_translate("CardRedactorWidget", "Лицевая сторона"))
        self.htmlToFromTextFrontPushButton.setText(_translate("CardRedactorWidget", "Text"))
        self.reverseSideEditor.setPlaceholderText(_translate("CardRedactorWidget", "Обратная сторона"))
        self.htmlToFromTextReversePushButton.setText(_translate("CardRedactorWidget", "Text"))
        self.savePushButton.setText(_translate("CardRedactorWidget", "СОХРАНИТЬ"))
import resources.qrc_resources_rc
