# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_CardWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CardWidget(object):
    def setupUi(self, CardWidget):
        CardWidget.setObjectName("CardWidget")
        CardWidget.resize(285, 370)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CardWidget.sizePolicy().hasHeightForWidth())
        CardWidget.setSizePolicy(sizePolicy)
        CardWidget.setMinimumSize(QtCore.QSize(200, 350))
        CardWidget.setStyleSheet("QWidget#DeckWidget {\n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(CardWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.deletePushButton = QtWidgets.QPushButton(CardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deletePushButton.sizePolicy().hasHeightForWidth())
        self.deletePushButton.setSizePolicy(sizePolicy)
        self.deletePushButton.setStyleSheet("QPushButton#deletePushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#deletePushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#deletePushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.deletePushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deletePushButton.setIcon(icon)
        self.deletePushButton.setIconSize(QtCore.QSize(30, 30))
        self.deletePushButton.setObjectName("deletePushButton")
        self.horizontalLayout.addWidget(self.deletePushButton)
        self.editPushButton = QtWidgets.QPushButton(CardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editPushButton.sizePolicy().hasHeightForWidth())
        self.editPushButton.setSizePolicy(sizePolicy)
        self.editPushButton.setStyleSheet("QPushButton#editPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#editPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#editPushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.editPushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/correction.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editPushButton.setIcon(icon1)
        self.editPushButton.setIconSize(QtCore.QSize(30, 30))
        self.editPushButton.setObjectName("editPushButton")
        self.horizontalLayout.addWidget(self.editPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titleOfDeckTextBrowser = QtWidgets.QTextBrowser(CardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleOfDeckTextBrowser.sizePolicy().hasHeightForWidth())
        self.titleOfDeckTextBrowser.setSizePolicy(sizePolicy)
        self.titleOfDeckTextBrowser.setMinimumSize(QtCore.QSize(0, 250))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.titleOfDeckTextBrowser.setFont(font)
        self.titleOfDeckTextBrowser.setStyleSheet("QTextBrowser#titleOfDeckTextBrowser {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border-radius: 0px;\n"
"}")
        self.titleOfDeckTextBrowser.setObjectName("titleOfDeckTextBrowser")
        self.horizontalLayout_3.addWidget(self.titleOfDeckTextBrowser)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(1, 4)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(CardWidget)
        QtCore.QMetaObject.connectSlotsByName(CardWidget)

    def retranslateUi(self, CardWidget):
        _translate = QtCore.QCoreApplication.translate
        CardWidget.setWindowTitle(_translate("CardWidget", "Form"))
        self.titleOfDeckTextBrowser.setHtml(_translate("CardWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:18pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
import resources.qrc_resources_rc
