# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_DeckWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeckWidget(object):
    def setupUi(self, DeckWidget):
        DeckWidget.setObjectName("DeckWidget")
        DeckWidget.resize(279, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DeckWidget.sizePolicy().hasHeightForWidth())
        DeckWidget.setSizePolicy(sizePolicy)
        DeckWidget.setMinimumSize(QtCore.QSize(250, 0))
        DeckWidget.setMaximumSize(QtCore.QSize(16777215, 400))
        DeckWidget.setStyleSheet("QWidget#DeckWidget {\n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(DeckWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.deletePushButton = QtWidgets.QPushButton(DeckWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deletePushButton.sizePolicy().hasHeightForWidth())
        self.deletePushButton.setSizePolicy(sizePolicy)
        self.deletePushButton.setStyleSheet("QPushButton#deletePushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#deletePushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#deletePushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.deletePushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deletePushButton.setIcon(icon)
        self.deletePushButton.setIconSize(QtCore.QSize(30, 30))
        self.deletePushButton.setObjectName("deletePushButton")
        self.horizontalLayout.addWidget(self.deletePushButton)
        self.editPushButton = QtWidgets.QPushButton(DeckWidget)
        self.editPushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editPushButton.sizePolicy().hasHeightForWidth())
        self.editPushButton.setSizePolicy(sizePolicy)
        self.editPushButton.setStyleSheet("QPushButton#editPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#editPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#editPushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.editPushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/correction.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editPushButton.setIcon(icon1)
        self.editPushButton.setIconSize(QtCore.QSize(30, 30))
        self.editPushButton.setObjectName("editPushButton")
        self.horizontalLayout.addWidget(self.editPushButton)
        self.cardsOfDeckPushButton = QtWidgets.QPushButton(DeckWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardsOfDeckPushButton.sizePolicy().hasHeightForWidth())
        self.cardsOfDeckPushButton.setSizePolicy(sizePolicy)
        self.cardsOfDeckPushButton.setStyleSheet("QPushButton#cardsOfDeckPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#cardsOfDeckPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#cardsOfDeckPushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.cardsOfDeckPushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/cards.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cardsOfDeckPushButton.setIcon(icon2)
        self.cardsOfDeckPushButton.setIconSize(QtCore.QSize(30, 30))
        self.cardsOfDeckPushButton.setObjectName("cardsOfDeckPushButton")
        self.horizontalLayout.addWidget(self.cardsOfDeckPushButton)
        self.statsPushButton = QtWidgets.QPushButton(DeckWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsPushButton.sizePolicy().hasHeightForWidth())
        self.statsPushButton.setSizePolicy(sizePolicy)
        self.statsPushButton.setStyleSheet("QPushButton#statsPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#statsPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#statsPushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.statsPushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/stats.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statsPushButton.setIcon(icon3)
        self.statsPushButton.setIconSize(QtCore.QSize(30, 30))
        self.statsPushButton.setObjectName("statsPushButton")
        self.horizontalLayout.addWidget(self.statsPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_2 = QtWidgets.QFrame(DeckWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.playPushButton = QtWidgets.QPushButton(DeckWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playPushButton.sizePolicy().hasHeightForWidth())
        self.playPushButton.setSizePolicy(sizePolicy)
        self.playPushButton.setStyleSheet("QPushButton#playPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#playPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#playPushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.playPushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playPushButton.setIcon(icon4)
        self.playPushButton.setIconSize(QtCore.QSize(30, 30))
        self.playPushButton.setObjectName("playPushButton")
        self.verticalLayout_3.addWidget(self.playPushButton)
        self.line_3 = QtWidgets.QFrame(DeckWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.titleOfDeckTextBrowser = QtWidgets.QTextBrowser(DeckWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleOfDeckTextBrowser.sizePolicy().hasHeightForWidth())
        self.titleOfDeckTextBrowser.setSizePolicy(sizePolicy)
        self.titleOfDeckTextBrowser.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.titleOfDeckTextBrowser.setFont(font)
        self.titleOfDeckTextBrowser.setStyleSheet("QTextBrowser#titleOfDeckTextBrowser {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border-radius: 0px;\n"
"}")
        self.titleOfDeckTextBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.titleOfDeckTextBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.titleOfDeckTextBrowser.setObjectName("titleOfDeckTextBrowser")
        self.verticalLayout_3.addWidget(self.titleOfDeckTextBrowser)
        self.line = QtWidgets.QFrame(DeckWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.infoTextEdit = QtWidgets.QTextEdit(DeckWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoTextEdit.sizePolicy().hasHeightForWidth())
        self.infoTextEdit.setSizePolicy(sizePolicy)
        self.infoTextEdit.setMaximumSize(QtCore.QSize(16777215, 70))
        self.infoTextEdit.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.infoTextEdit.setFont(font)
        self.infoTextEdit.setStyleSheet("QTextEdit#infoTextEdit {\n"
"    background-color: rgb(210, 210, 210);\n"
"    border-radius: 0px;\n"
"}")
        self.infoTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.infoTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.infoTextEdit.setReadOnly(True)
        self.infoTextEdit.setObjectName("infoTextEdit")
        self.verticalLayout_3.addWidget(self.infoTextEdit)
        self.verticalLayout_3.setStretch(3, 5)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.setStretch(1, 4)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DeckWidget)
        QtCore.QMetaObject.connectSlotsByName(DeckWidget)

    def retranslateUi(self, DeckWidget):
        _translate = QtCore.QCoreApplication.translate
        DeckWidget.setWindowTitle(_translate("DeckWidget", "Form"))
        self.titleOfDeckTextBrowser.setHtml(_translate("DeckWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:18pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.infoTextEdit.setHtml(_translate("DeckWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
import resources.qrc_resources_rc
