# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_RepeatWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RepeatWindow(object):
    def setupUi(self, RepeatWindow):
        RepeatWindow.setObjectName("RepeatWindow")
        RepeatWindow.resize(1008, 726)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        RepeatWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(RepeatWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.goBackPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.goBackPushButton.setMinimumSize(QtCore.QSize(210, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.goBackPushButton.setFont(font)
        self.goBackPushButton.setStyleSheet("QPushButton#goBackPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QPushButton#goBackPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton#goBackPushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/go_back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.goBackPushButton.setIcon(icon)
        self.goBackPushButton.setIconSize(QtCore.QSize(40, 40))
        self.goBackPushButton.setObjectName("goBackPushButton")
        self.horizontalLayout_4.addWidget(self.goBackPushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frontSideTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.frontSideTextBrowser.setObjectName("frontSideTextBrowser")
        self.horizontalLayout_2.addWidget(self.frontSideTextBrowser)
        self.reverseSideTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.reverseSideTextBrowser.setFont(font)
        self.reverseSideTextBrowser.setStyleSheet("background-color: rgb(130, 130, 130)")
        self.reverseSideTextBrowser.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.reverseSideTextBrowser.setObjectName("reverseSideTextBrowser")
        self.horizontalLayout_2.addWidget(self.reverseSideTextBrowser)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(200, -1, 200, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.showAnswerPushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showAnswerPushButton.sizePolicy().hasHeightForWidth())
        self.showAnswerPushButton.setSizePolicy(sizePolicy)
        self.showAnswerPushButton.setMinimumSize(QtCore.QSize(200, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.showAnswerPushButton.setFont(font)
        self.showAnswerPushButton.setStyleSheet("QPushButton#showAnswerPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(130, 130, 130);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#showAnswerPushButton:pressed {\n"
"    background-color: rgb(110, 110, 110);\n"
"}\n"
"\n"
"QPushButton#showAnswerPushButton:hover {\n"
"    background-color: rgb(110, 110, 110);\n"
"}")
        self.showAnswerPushButton.setObjectName("showAnswerPushButton")
        self.horizontalLayout_3.addWidget(self.showAnswerPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.zeroPushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zeroPushButton.sizePolicy().hasHeightForWidth())
        self.zeroPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.zeroPushButton.setFont(font)
        self.zeroPushButton.setStyleSheet("QPushButton#zeroPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(245, 245, 245);\n"
"    color: rgb(15, 15, 15);\n"
"}\n"
"\n"
"QPushButton#zeroPushButton:pressed {\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"\n"
"QPushButton#zeroPushButton:hover {\n"
"    background-color: rgb(220, 220, 220);\n"
"}")
        self.zeroPushButton.setObjectName("zeroPushButton")
        self.horizontalLayout.addWidget(self.zeroPushButton)
        self.onePushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.onePushButton.sizePolicy().hasHeightForWidth())
        self.onePushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.onePushButton.setFont(font)
        self.onePushButton.setStyleSheet("QPushButton#onePushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(199, 199, 199);\n"
"    color: rgb(61, 61, 61)\n"
"}\n"
"\n"
"QPushButton#onePushButton:pressed {\n"
"    background-color: rgb(179, 179, 179);\n"
"}\n"
"\n"
"QPushButton#onePushButton:hover {\n"
"    background-color: rgb(179, 179, 179);\n"
"}")
        self.onePushButton.setObjectName("onePushButton")
        self.horizontalLayout.addWidget(self.onePushButton)
        self.twoPushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twoPushButton.sizePolicy().hasHeightForWidth())
        self.twoPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.twoPushButton.setFont(font)
        self.twoPushButton.setStyleSheet("QPushButton#twoPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(153, 153, 153);\n"
"    color: rgb(107, 107, 107);\n"
"}\n"
"\n"
"QPushButton#twoPushButton:pressed {\n"
"    background-color: rgb(133, 133, 133);\n"
"}\n"
"\n"
"QPushButton#twoPushButton:hover {\n"
"    background-color: rgb(133, 133, 133);\n"
"}")
        self.twoPushButton.setObjectName("twoPushButton")
        self.horizontalLayout.addWidget(self.twoPushButton)
        self.threePushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threePushButton.sizePolicy().hasHeightForWidth())
        self.threePushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.threePushButton.setFont(font)
        self.threePushButton.setStyleSheet("QPushButton#threePushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(107, 107, 107);\n"
"    color: rgb(153, 153, 153);\n"
"}\n"
"\n"
"QPushButton#threePushButton:pressed {\n"
"    background-color: rgb(87, 87, 87);\n"
"}\n"
"\n"
"QPushButton#threePushButton:hover {\n"
"    background-color: rgb(87, 87, 87);\n"
"}")
        self.threePushButton.setObjectName("threePushButton")
        self.horizontalLayout.addWidget(self.threePushButton)
        self.fourPushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fourPushButton.sizePolicy().hasHeightForWidth())
        self.fourPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.fourPushButton.setFont(font)
        self.fourPushButton.setStyleSheet("QPushButton#fourPushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(61, 61, 61);\n"
"    color: rgb(199, 199, 199);\n"
"}\n"
"\n"
"QPushButton#fourPushButton:pressed {\n"
"    background-color: rgb(46, 46, 46);\n"
"}\n"
"\n"
"QPushButton#fourPushButton:hover {\n"
"    background-color: rgb(46, 46, 46);\n"
"}")
        self.fourPushButton.setObjectName("fourPushButton")
        self.horizontalLayout.addWidget(self.fourPushButton)
        self.fivePushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fivePushButton.sizePolicy().hasHeightForWidth())
        self.fivePushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.fivePushButton.setFont(font)
        self.fivePushButton.setAccessibleDescription("")
        self.fivePushButton.setStyleSheet("QPushButton#fivePushButton {\n"
"    border-radius: 0 px;\n"
"    background-color: rgb(15, 15, 15);\n"
"    color: rgb(245, 245, 245);\n"
"}\n"
"\n"
"QPushButton#fivePushButton:pressed {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton#fivePushButton:hover {\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.fivePushButton.setCheckable(False)
        self.fivePushButton.setFlat(False)
        self.fivePushButton.setObjectName("fivePushButton")
        self.horizontalLayout.addWidget(self.fivePushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        RepeatWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RepeatWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1008, 26))
        self.menubar.setObjectName("menubar")
        RepeatWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RepeatWindow)
        self.statusbar.setObjectName("statusbar")
        RepeatWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RepeatWindow)
        QtCore.QMetaObject.connectSlotsByName(RepeatWindow)

    def retranslateUi(self, RepeatWindow):
        _translate = QtCore.QCoreApplication.translate
        RepeatWindow.setWindowTitle(_translate("RepeatWindow", "Повторение колоды"))
        self.goBackPushButton.setText(_translate("RepeatWindow", "В главное меню"))
        self.showAnswerPushButton.setText(_translate("RepeatWindow", "Показать ответ"))
        self.zeroPushButton.setText(_translate("RepeatWindow", "0"))
        self.onePushButton.setText(_translate("RepeatWindow", "1"))
        self.twoPushButton.setText(_translate("RepeatWindow", "2"))
        self.threePushButton.setText(_translate("RepeatWindow", "3"))
        self.fourPushButton.setText(_translate("RepeatWindow", "4"))
        self.fivePushButton.setText(_translate("RepeatWindow", "5"))
import resources.qrc_resources_rc
